name: Continuous Delivery
run-name: Updating site...
on: [push]
jobs:
  Update-Deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd content-nextjs
          npm i
          npm run build
      - name: Deploy
        run: |
          cd content-nextjs
          for pid in $(jobs -p); do kill $pid; done
          nohup ./startup.sh > /dev/null 2>&1 &
        # screen -S deployment -dm bash -c 'NODE_ENV=production npm run start'
        # screen -S deployment -X quit
